### ISSUE TITLE
aleatoric  uncertainty loss

### ISSUE THREAD

**Issue by linchunmian** [pmorerio/dl-uncertainty#4]
Hi, when I read your implementation, there are two problems confused me:
1. you mean log_loc_car has been passed through log function? If it is, where could I find the log computation in the code?
2. I confuse whether it needs to add activation function for var? Actually, I also encounter loss NaN issue, and there is no effective means to alleviate it, could you please give me some tricks?
Maybe you can help me in terms of these problems above.
Thanks in advance!

**Comment by pmorerio** [comment]
Hi, 

1. you do not find any  log computation because you are regressing the log of the variance. More detail in this other issue https://github.com/pmorerio/dl-uncertainty/issues/1#issuecomment-506680509

2.  I was not getting any NaN issue after removing activations.

**Comment by pmorerio** [comment]
Closing since duplicate and inactive for months.
