### ISSUE TITLE
Meaning of results in Aleatoric Uncertainty

### ISSUE THREAD

**Issue by ekagra-ranjan** [pmorerio/dl-uncertainty#6]
Hi @pmorerio ,

Thank you for building this repo! Your repo helps in understanding the paper. I have a small doubt in the interpretation of your results on MNIST in Aleatoric Uncertainty:

1) Is [generated image](https://github.com/pmorerio/dl-uncertainty/blob/master/aleatoric-uncertainty/pics/aleatoric_generated.png) the mean of the output distribution with variance as predicted by your [aleatoric uncertainity](https://github.com/pmorerio/dl-uncertainty/blob/master/aleatoric-uncertainty/pics/aleatoric_uncertainty.png)?

2) How does modelling the Aleatoric Uncertainty help in reconstruction? Are the reconstruction better than without using this loss function?

3) According to the paper, Aleatoic uncertainty models the noise in the input image. But I don't quite get how does the [Aleatoric Uncertainty](https://github.com/pmorerio/dl-uncertainty/blob/master/aleatoric-uncertainty/pics/aleatoric_uncertainty.png) correlate to noise in the [real image](https://github.com/pmorerio/dl-uncertainty/blob/master/aleatoric-uncertainty/pics/aleatoric_real.png). 

Can you please share your views on any or all of my doubts above? Thanks you in advance!

**Comment by pmorerio** [comment]
Hi, thanks for contributing to the discussion. Regarding your questions:

1. Yes. In fact I use the mean to save the images [here](https://github.com/pmorerio/dl-uncertainty/blob/5838384da97fb8084ace6877e88277ee80f9d7c1/aleatoric-uncertainty/model.py#L90)
2.  For this,  I cannot say. Honestly I do not think the paper does this claim.
3. According to the paper:
> Aleatoric Uncertainty captures noise inherent in the observations. This could be for example sensor noise or motion noise, resulting in uncertainty which cannot be reduced even if more data were to be collected

To my understanding this mainly relates to contours in MNIST, where shades of gray makes them uncertain. This is coherent with Fig 1(d) in the paper, where aleatoric uncertainty lies mainly on the semantic segmentation borders.

**Comment by ekagra-ranjan** [comment]
Your response strengthened my understanding! Thank you for sharing your insights :)
